apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: even-odd
spec:
  vertices:
    - name: in
      source:
        generator:
          # How many messages to generate in the duration.
          rpu: 1
          duration: 1s
          # Optional, size of each generated message, defaults to 10.
          msgSize: 1024
    - name: even-or-odd
      # containerTemplate:
      #   env:
      #     - name: NUMAFLOW_DEBUG
      #       value: "true"
      #     - name: NUMAFLOW_PPROF
      #       value: "true"
      scale:
        min: 1
      udf:
        container:
          image: even-odd:v0.5.0

        
              
    - name: number-sink
      scale:
        min: 1
      sink:
        log: {}
  edges:
    - from: in
      to: even-or-odd
    
    - from: even-or-odd
      to: number-sink
     



# kubectl port-forward even-odd-even-or-odd-0-kyhpl 2469

# │ even-odd-even-or-odd-0-kyhpl      ●  2/2   Running         0   3  53      3    n/a     42    n/a 10.42.0.30  lima-rancher-desktop  12m    │            │               │                 │                       │                             │                                        │

# Port forward the UI to https://localhost:8443/
# kubectl -n numaflow-system port-forward deployment/numaflow-server 8443:8443
# 